### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by phoe** [phoe/wordnet#1]
Contact the original author and ask them for the license this code should be distributed under.

**Comment by odanoburu** [comment]
hello! any news on this @phoe ?

**Comment by phoe** [comment]
The last mails I got tell me that the process is stuck at MIT paperwork. I will update this repository as soon as I know anything.

**Comment by odanoburu** [comment]
ok, thanks!

**Comment by phoe** [comment]
**FINALLY**

https://github.com/phoe/wordnet/commit/11b20b49e598eb6735b37db9c2ed1b032af9dee2
